In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

About this dataseter.

-There are 54 questions, labeled Atr1 to Atr54, corresponding to Question 1 to Question 52.

-The last column is the status column, which indicates whether the individual is 'Married' or 'Divorced'. It is represented by a Boolean variable, where 'Married' is represented as '1' and 'Divorced' as '0'."

Survey questions:
When one of our apologies apologizes when our discussions go in a bad direction, the issue does not extend.
I know we can ignore our differences, even if things get hard sometimes.
When we need it, we can take our discussions with my wife from the beginning and correct it.
When I argue with my wife, it will eventually work for me to contact him.
The time I spent with my wife is special for us.
We don't have time at home as partners.
We are like two strangers who share the same environment at home rather than family.
I enjoy our holidays with my wife.
I enjoy traveling with my wife.
My wife and most of our goals are common.
I think that one day in the future, when I look back, I see that my wife and I are in harmony with each other.
My wife and I have similar values in terms of personal freedom.
My husband and I have similar entertainment.
Most of our goals for people (children, friends, etc.) are the same.
Our dreams of living with my wife are similar and harmonious
We're compatible with my wife about what love should be
We share the same views with my wife about being happy in your life
My wife and I have similar ideas about how marriage should be
My wife and I have similar ideas about how roles should be in marriage
My wife and I have similar values in trust
I know exactly what my wife likes.
I know how my wife wants to be taken care of when she's sick.
I know my wife's favorite food.
I can tell you what kind of stress my wife is facing in her life.
I have knowledge of my wife's inner world.
I know my wife's basic concerns.
I know what my wife's current sources of stress are.
I know my wife's hopes and wishes.
I know my wife very well.
I know my wife's friends and their social relationships.
I feel aggressive when I argue with my wife.
When discussing with my wife, I usually use expressions such as …..
I can use negative statements about my wife's personality during our discussions.
I can use offensive expressions during our discussions.
I can insult our discussions.
I can be humiliating when we argue.
My argument with my wife is not calm.
I hate my wife's way of bringing it up.
Fights often occur suddenly.
We're just starting a fight before I know what's going on.
When I talk to my wife about something, my calm suddenly breaks.
When I argue with my wife, it only snaps in and I don't say a word.
I'm mostly thirsty to calm the environment a little bit.
Sometimes I think it's good for me to leave home for a while.
I'd rather stay silent than argue with my wife.
Even if I'm right in the argument, I'm thirsty not to upset the other side.
When I argue with my wife, I remain silent because I am afraid of not being able to control my anger.
I feel right in our discussions.
I have nothing to do with what I've been accused of.
I'm not actually the one who's guilty about what I'm accused of.
I'm not the one who's wrong about problems at home.
I wouldn't hesitate to tell her about my wife's inadequacy.
When I discuss it, I remind her of my wife's inadequate issues.
I'm not afraid to tell her about my wife's incompetence.

In [2]:
df = pd.read_csv(r'C:\Users\ADMIN\OneDrive\Desktop\data analytics\analyst HQ\divorce.csv', delimiter = ';')
df.head(5)

Atr1  Atr2  Atr3  Atr4  Atr5  Atr6  Atr7  Atr8  Atr9  Atr10  ...  Atr46  \
0     2     2     4     1     0     0     0     0     0      0  ...      2   
1     4     4     4     4     4     0     0     4     4      4  ...      2   
2     2     2     2     2     1     3     2     1     1      2  ...      3   
3     3     2     3     2     3     3     3     3     3      3  ...      2   
4     2     2     1     1     1     1     0     0     0      0  ...      2   

   Atr47  Atr48  Atr49  Atr50  Atr51  Atr52  Atr53  Atr54  Class  
0      1      3      3      3      2      3      2      1      1  
1      2      3      4      4      4      4      2      2      1  
2      2      3      1      1      1      2      2      2      1  
3      2      3      3      3      3      2      2      2      1  
4      1      2      3      2      2      2      1      0      1  

[5 rows x 55 columns]

In [3]:
df.shape

(170, 55)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 170 entries, 0 to 169
Data columns (total 55 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Atr1    170 non-null    int64
 1   Atr2    170 non-null    int64
 2   Atr3    170 non-null    int64
 3   Atr4    170 non-null    int64
 4   Atr5    170 non-null    int64
 5   Atr6    170 non-null    int64
 6   Atr7    170 non-null    int64
 7   Atr8    170 non-null    int64
 8   Atr9    170 non-null    int64
 9   Atr10   170 non-null    int64
 10  Atr11   170 non-null    int64
 11  Atr12   170 non-null    int64
 12  Atr13   170 non-null    int64
 13  Atr14   170 non-null    int64
 14  Atr15   170 non-null    int64
 15  Atr16   170 non-null    int64
 16  Atr17   170 non-null    int64
 17  Atr18   170 non-null    int64
 18  Atr19   170 non-null    int64
 19  Atr20   170 non-null    int64
 20  Atr21   170 non-null    int64
 21  Atr22   170 non-null    int64
 22  Atr23   170 non-null    int64
 23  Atr24   170 non

In [5]:
df.describe()

Atr1        Atr2        Atr3        Atr4        Atr5        Atr6  \
count  170.000000  170.000000  170.000000  170.000000  170.000000  170.000000   
mean     1.776471    1.652941    1.764706    1.482353    1.541176    0.747059   
std      1.627257    1.468654    1.415444    1.504327    1.632169    0.904046   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
50%      2.000000    2.000000    2.000000    1.000000    1.000000    0.000000   
75%      3.000000    3.000000    3.000000    3.000000    3.000000    1.000000   
max      4.000000    4.000000    4.000000    4.000000    4.000000    4.000000   

             Atr7        Atr8        Atr9       Atr10  ...       Atr46  \
count  170.000000  170.000000  170.000000  170.000000  ...  170.000000   
mean     0.494118    1.452941    1.458824    1.576471  ...    2.552941   
std      0.898698    1.546371    1.557976    1.421529  ...    1.371786   
min      0.000000    0.000000    0.000000    0.000000  ...    0.000000   
25%      0.000000    0.000000    0.000000    0.000000  ...    2.000000   
50%      0.000000    1.000000    1.000000    2.000000  ...    3.000000   
75%      1.000000    3.000000    3.000000    3.000000  ...    4.000000   
max      4.000000    4.000000    4.000000    4.000000  ...    4.000000   

            Atr47       Atr48       Atr49       Atr50       Atr51       Atr52  \
count  170.000000  170.000000  170.000000  170.000000  170.000000  170.000000   
mean     2.270588    2.741176    2.382353    2.429412    2.476471    2.517647   
std      1.586841    1.137348    1.511587    1.405090    1.260238    1.476537   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      1.000000    2.000000    1.000000    1.000000    2.000000    1.000000   
50%      2.000000    3.000000    3.000000    2.000000    3.000000    3.000000   
75%      4.000000    4.000000    4.000000    4.000000    4.000000    4.000000   
max      4.000000    4.000000    4.000000    4.000000    4.000000    4.000000   

            Atr53       Atr54       Class  
count  170.000000  170.000000  170.000000  
mean     2.241176    2.011765    0.494118  
std      1.505634    1.667611    0.501442  
min      0.000000    0.000000    0.000000  
25%      1.000000    0.000000    0.000000  
50%      2.000000    2.000000    0.000000  
75%      4.000000    4.000000    1.000000  
max      4.000000    4.000000    1.000000  

[8 rows x 55 columns]

In [6]:
df.isna().sum()

Atr1     0
Atr2     0
Atr3     0
Atr4     0
Atr5     0
Atr6     0
Atr7     0
Atr8     0
Atr9     0
Atr10    0
Atr11    0
Atr12    0
Atr13    0
Atr14    0
Atr15    0
Atr16    0
Atr17    0
Atr18    0
Atr19    0
Atr20    0
Atr21    0
Atr22    0
Atr23    0
Atr24    0
Atr25    0
Atr26    0
Atr27    0
Atr28    0
Atr29    0
Atr30    0
Atr31    0
Atr32    0
Atr33    0
Atr34    0
Atr35    0
Atr36    0
Atr37    0
Atr38    0
Atr39    0
Atr40    0
Atr41    0
Atr42    0
Atr43    0
Atr44    0
Atr45    0
Atr46    0
Atr47    0
Atr48    0
Atr49    0
Atr50    0
Atr51    0
Atr52    0
Atr53    0
Atr54    0
Class    0
dtype: int64

In [7]:
#DUPLICATES
df.drop_duplicates()

Atr1  Atr2  Atr3  Atr4  Atr5  Atr6  Atr7  Atr8  Atr9  Atr10  ...  Atr46  \
0       2     2     4     1     0     0     0     0     0      0  ...      2   
1       4     4     4     4     4     0     0     4     4      4  ...      2   
2       2     2     2     2     1     3     2     1     1      2  ...      3   
3       3     2     3     2     3     3     3     3     3      3  ...      2   
4       2     2     1     1     1     1     0     0     0      0  ...      2   
..    ...   ...   ...   ...   ...   ...   ...   ...   ...    ...  ...    ...   
165     0     0     0     0     0     0     0     0     0      0  ...      1   
166     0     0     0     0     0     0     0     0     0      0  ...      4   
167     1     1     0     0     0     0     0     0     0      1  ...      3   
168     0     0     0     0     0     0     0     0     0      0  ...      3   
169     0     0     0     0     0     0     0     1     0      0  ...      3   

     Atr47  Atr48  Atr49  Atr50  Atr51  Atr52  Atr53  Atr54  Class  
0        1      3      3      3      2      3      2      1      1  
1        2      3      4      4      4      4      2      2      1  
2        2      3      1      1      1      2      2      2      1  
3        2      3      3      3      3      2      2      2      1  
4        1      2      3      2      2      2      1      0      1  
..     ...    ...    ...    ...    ...    ...    ...    ...    ...  
165      0      4      1      1      4      2      2      2      0  
166      1      2      2      2      2      3      2      2      0  
167      0      2      0      1      1      3      0      0      0  
168      3      2      2      3      2      4      3      1      0  
169      4      4      0      1      3      3      3      1      0  

[150 rows x 55 columns]

In [8]:
df.shape

(170, 55)

In [9]:
df.columns

Index(['Atr1', 'Atr2', 'Atr3', 'Atr4', 'Atr5', 'Atr6', 'Atr7', 'Atr8', 'Atr9',
       'Atr10', 'Atr11', 'Atr12', 'Atr13', 'Atr14', 'Atr15', 'Atr16', 'Atr17',
       'Atr18', 'Atr19', 'Atr20', 'Atr21', 'Atr22', 'Atr23', 'Atr24', 'Atr25',
       'Atr26', 'Atr27', 'Atr28', 'Atr29', 'Atr30', 'Atr31', 'Atr32', 'Atr33',
       'Atr34', 'Atr35', 'Atr36', 'Atr37', 'Atr38', 'Atr39', 'Atr40', 'Atr41',
       'Atr42', 'Atr43', 'Atr44', 'Atr45', 'Atr46', 'Atr47', 'Atr48', 'Atr49',
       'Atr50', 'Atr51', 'Atr52', 'Atr53', 'Atr54', 'Class'],
      dtype='object')

In [10]:
df['Class'].nunique()

2

In [11]:
df['Class'].value_counts()

Class
0    86
1    84
Name: count, dtype: int64

In [12]:
y = df['Class']
X = df.drop('Class',axis=1)

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2 , random_state=3)

In [14]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(136, 54)
(34, 54)
(136,)
(34,)


In [15]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()

In [16]:
knn.fit(X=X_train, y=y_train)

KNeighborsClassifier()

In [17]:
predicted = knn.predict(X = X_test)
expected = y_test

In [18]:
expected[:20]

98     0
86     0
143    0
15     1
42     1
38     1
41     1
83     1
155    0
64     1
6      1
76     1
25     1
3      1
89     0
117    0
134    0
159    0
47     1
114    0
Name: Class, dtype: int64

In [19]:
predicted[:20]

array([0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0],
      dtype=int64)

In [20]:
#USE A LIST COMPRESSION TO FIND ANY WRONG PREDICTIONS
wrong_pred = [(p, e) for (p, e) in zip(predicted, expected) if p != e]

In [21]:
wrong_pred #knn wrongly predicted 1 out of our 34 values

[(0, 1)]

In [22]:
print(f'{knn.score(X_test, y_test):.2%}')

97.06%


In [23]:
#K FOLD CROSS EXAMINATION
from sklearn.model_selection import KFold

kfold = KFold(n_splits=5, random_state = 8, shuffle=True)
#n_splits=5 specifies the numbers of folds
#random_state=3 seeds the random number generated for reproducability
#shuffles=True cause the kfold object to randomize the data by shuffling it before splitting it into folds


In [24]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(estimator = knn, X=X_test,
                         y=y_test, cv=kfold)

In [25]:
scores

array([1.        , 1.        , 1.        , 1.        , 0.83333333])

In [26]:
scores.mean()

0.9666666666666666

In [27]:
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.linear_model import LogisticRegression, SGDClassifier, Perceptron, RidgeClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import log_loss
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix



In [28]:
estimators = {
    'Decision Tree' : DecisionTreeClassifier(random_state=3),
    'Random Forest' : RandomForestClassifier(random_state=3),
    'Extra Tree' : ExtraTreesClassifier(random_state=3),
    'Gradient Boost' : GradientBoostingClassifier(random_state=3),
    'AdaBoost' : AdaBoostClassifier(random_state=3),
    'Logistic Regression' : LogisticRegression(random_state=3),
    'SGDC' : SGDClassifier(random_state=3),
    'Ridge' : RidgeClassifier(random_state=3)
}

In [30]:
model_names = []
accuracies = []

In [29]:
for name, model in estimators.items():
    model.fit(X_train, y_train)
    y_pred= model.predict(X_test)
    # Print the model name
    print(f'{name}')
    # Print the accuracy score
    print(f' Accuracy: {accuracy_score(y_test, y_pred):.3f}')
    # Print the confusion matrix
    print(f' Confusion Matrix: \n{confusion_matrix(y_test, y_pred)}')
    # Print the classification report
    print(f' Report: \n{classification_report(y_test, y_pred)}')
    print("*" * 100)

Decision Tree
 Accuracy: 1.000
 Confusion Matrix: 
[[16  0]
 [ 0 18]]
 Report: 
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      1.00      1.00        18

    accuracy                           1.00        34
   macro avg       1.00      1.00      1.00        34
weighted avg       1.00      1.00      1.00        34

****************************************************************************************************
Random Forest
 Accuracy: 0.971
 Confusion Matrix: 
[[16  0]
 [ 1 17]]
 Report: 
              precision    recall  f1-score   support

           0       0.94      1.00      0.97        16
           1       1.00      0.94      0.97        18

    accuracy                           0.97        34
   macro avg       0.97      0.97      0.97        34
weighted avg       0.97      0.97      0.97        34

*************************************************************************************

C:\Users\ADMIN\AppData\Roaming\Python\Python311\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


Logistic Regression
 Accuracy: 0.971
 Confusion Matrix: 
[[16  0]
 [ 1 17]]
 Report: 
              precision    recall  f1-score   support

           0       0.94      1.00      0.97        16
           1       1.00      0.94      0.97        18

    accuracy                           0.97        34
   macro avg       0.97      0.97      0.97        34
weighted avg       0.97      0.97      0.97        34

****************************************************************************************************
SGDC
 Accuracy: 1.000
 Confusion Matrix: 
[[16  0]
 [ 0 18]]
 Report: 
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      1.00      1.00        18

    accuracy                           1.00        34
   macro avg       1.00      1.00      1.00        34
weighted avg       1.00      1.00      1.00        34

****************************************************************************************